apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# 由 controller-gen 从 kubebuilder:rbac 标记生成的 ClusterRole
- role.yaml
- service_account.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- role_binding.yaml
