//go:build !ignore_autogenerated

// Copyright 2026 balcony314.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Marker) DeepCopyInto(out *Marker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Marker.
func (in *Marker) DeepCopy() *Marker {
	if in == nil {
		return nil
	}
	out := new(Marker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryPolicy) DeepCopyInto(out *MemoryPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryPolicy.
func (in *MemoryPolicy) DeepCopy() *MemoryPolicy {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemoryPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryPolicyList) DeepCopyInto(out *MemoryPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MemoryPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryPolicyList.
func (in *MemoryPolicyList) DeepCopy() *MemoryPolicyList {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemoryPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryPolicySpec) DeepCopyInto(out *MemoryPolicySpec) {
	*out = *in
	out.Marker = in.Marker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryPolicySpec.
func (in *MemoryPolicySpec) DeepCopy() *MemoryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryPolicyStatus) DeepCopyInto(out *MemoryPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryPolicyStatus.
func (in *MemoryPolicyStatus) DeepCopy() *MemoryPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
