---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-memory-example-com-v1-memorypolicy
  failurePolicy: Fail
  name: vmemorypolicy-v1.kb.io
  rules:
  - apiGroups:
    - memory.example.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - memorypolicies
  sideEffects: None
