//go:build !ignore_autogenerated

/*
Copyright 2026 The OAM Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnit) DeepCopyInto(out *DeployUnit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnit.
func (in *DeployUnit) DeepCopy() *DeployUnit {
	if in == nil {
		return nil
	}
	out := new(DeployUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeployUnit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitComponent) DeepCopyInto(out *DeployUnitComponent) {
	*out = *in
	in.Properties.DeepCopyInto(&out.Properties)
	if in.Traits != nil {
		in, out := &in.Traits, &out.Traits
		*out = make([]DeployUnitTrait, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitComponent.
func (in *DeployUnitComponent) DeepCopy() *DeployUnitComponent {
	if in == nil {
		return nil
	}
	out := new(DeployUnitComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitHistory) DeepCopyInto(out *DeployUnitHistory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitHistory.
func (in *DeployUnitHistory) DeepCopy() *DeployUnitHistory {
	if in == nil {
		return nil
	}
	out := new(DeployUnitHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeployUnitHistory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitHistoryList) DeepCopyInto(out *DeployUnitHistoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeployUnitHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitHistoryList.
func (in *DeployUnitHistoryList) DeepCopy() *DeployUnitHistoryList {
	if in == nil {
		return nil
	}
	out := new(DeployUnitHistoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeployUnitHistoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitHistorySpec) DeepCopyInto(out *DeployUnitHistorySpec) {
	*out = *in
	in.DeployUnit.DeepCopyInto(&out.DeployUnit)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitHistorySpec.
func (in *DeployUnitHistorySpec) DeepCopy() *DeployUnitHistorySpec {
	if in == nil {
		return nil
	}
	out := new(DeployUnitHistorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitHistoryStatus) DeepCopyInto(out *DeployUnitHistoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitHistoryStatus.
func (in *DeployUnitHistoryStatus) DeepCopy() *DeployUnitHistoryStatus {
	if in == nil {
		return nil
	}
	out := new(DeployUnitHistoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitList) DeepCopyInto(out *DeployUnitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeployUnit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitList.
func (in *DeployUnitList) DeepCopy() *DeployUnitList {
	if in == nil {
		return nil
	}
	out := new(DeployUnitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeployUnitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitSpec) DeepCopyInto(out *DeployUnitSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]DeployUnitComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitSpec.
func (in *DeployUnitSpec) DeepCopy() *DeployUnitSpec {
	if in == nil {
		return nil
	}
	out := new(DeployUnitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitStatus) DeepCopyInto(out *DeployUnitStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitStatus.
func (in *DeployUnitStatus) DeepCopy() *DeployUnitStatus {
	if in == nil {
		return nil
	}
	out := new(DeployUnitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployUnitTrait) DeepCopyInto(out *DeployUnitTrait) {
	*out = *in
	in.Properties.DeepCopyInto(&out.Properties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployUnitTrait.
func (in *DeployUnitTrait) DeepCopy() *DeployUnitTrait {
	if in == nil {
		return nil
	}
	out := new(DeployUnitTrait)
	in.DeepCopyInto(out)
	return out
}
