# acc 配置文件
# 注释以 '#' 或 '[' 开头

log_level 0
log_path ./logs/
enable_daemon no
worker_process 2
connections_per_worker 1024

server 127.0.0.1
tcp_port 1883
tls_port 8883
cert_file conf/cert.pem
key_file  conf/key.pem

accept_mutex no
accept_mutex_delay_ms 500
client_timeout 300s
max_read_buffer_size 1m
max_open_fd 65536

thread_pool_thread_num 4
thread_pool_queue_size 1000
metrics_dir ./metrics/
